1、异常
2、Java异常类架构
3、异常处理
4、抛出异常
5、捕获异常
6、自定义异常
7、异常链



1、异常
异常就是程序上的错误，我们在编写程序的时候经常会产生错误，这些错误划分为编译期间的错误和运行期间的错误。

2、Java异常类架构
在 Java 中，通过 Throwable 及其子类来描述各种不同类型的异常。如下是 Java 异常类的架构图（不是全部，只展示部分类）：![img](http://img.mukewang.com/wiki/5ec46e9f098c833310400588.jpg)

1、Throwable 类：Throwable 位于 java.lang 包下，它是 Java 语言中所有错误（Error）和异常（Exception）的父类。Throwable 包含了其线程创建时线程执行堆栈的快照，它提供了 printStackTrace() 等接口用于获取堆栈跟踪数据等信息。主要方法：

- fillInStackTrace： 用当前的调用栈层次填充 Throwable 对象栈层次，添加到栈层次任何先前信息中；

- getMessage：返回关于发生的异常的详细信息。这个消息在 Throwable 类的构造函数中初始化了；

- getCause：返回一个 Throwable 对象代表异常原因；

- getStackTrace：返回一个包含堆栈层次的数组。下标为 0 的元素代表栈顶，最后一个元素代表方法调用堆栈的栈底；

- printStackTrace：打印 toString() 结果和栈层次到 System.err，即错误输出流。

  

2、Error 类：Error 是 Throwable 的一个直接子类，它可以指示合理的应用程序不应该尝试捕获的严重问题。这些错误在应用程序的控制和处理能力之外，编译器不会检查 Error，对于设计合理的应用程序来说，即使发生了错误，本质上也无法通过异常处理来解决其所引起的异常状况。
常见Error：

-  AssertionError：断言错误；
- VirtualMachineError：虚拟机错误；
- UnsupportedClassVersionError：  Java 类版本错误；
- OutOfMemoryError ：内存溢出错误。

3、 Exception 类：Exception 是 Throwable 的一个直接子类。它指示合理的应用程序可能希望捕获的条件。Exception 又包括 Unchecked Exception（非检查异常）和 Checked Exception（检查异常）两大类别。

- Unchecked Exception （非检查异常）Unchecked Exception 是编译器不要求强制处理的异常，包含 RuntimeException 以及它的相关子类。我们编写代码时即使不去处理此类异常，程序还是会编译通过。常见非检查异常：

  ​	NullPointerException：空指针异常；

  ​	ArithmeticException：算数异常；

  ​	ArrayIndexOutOfBoundsException：数组下标越界异常；

  ​	ClassCastException：类型转换异常。

-  Checked Exception（检查异常）Checked Exception 是编译器要求必须处理的异常，除了 RuntimeException 以及它的子类，都是 Checked Exception 异常。我们在程序编写时就必须处理此类异常，否则程序无法编译通过。常见检查异常：
  IOException： IO 异常
  SQLException： SQL 异常

3、异常处理
在 Java 语言中，异常处理机制可以分为两部分：

- 抛出异常：当一个方法发生错误时，会创建一个异常对象，并交给运行时系统处理；
- 捕获异常：在方法抛出异常之后，运行时系统将转为寻找合适的异常处理器。

Java 通过 5 个关键字来实现异常处理，分别是：throw、throws、try、catch、finally。

4、抛出异常
(1)throw
(2)throws

5、捕获异常

1. try 语句块：用于监听异常，当发生异常时，异常就会被抛出；
2. catch 语句块：catch 语句包含要捕获的异常类型的声明，当 try 语句块发生异常时，catch 语句块就会被检查。当 catch 块尝试捕获异常时，是按照 catch 块的声明顺序从上往下寻找的，一旦匹配，就不会再向下执行。因此，如果同一个 try 块下的多个 catch 异常类型有父子关系，应该将子类异常放在前面，父类异常放在后面；
3. finally 语句块：无论是否发生异常，都会执行 finally 语句块。finally 常用于这样的场景：由于 finally 语句块总是会被执行，所以那些在 try 代码块中打开的，并且必须回收的物理资源（如数据库连接、网络连接和文件），一般会放在 finally 语句块中释放资源。
4. try 语句块后可以接零个或多个 catch 语句块，如果没有 catch 块，则必须跟一个 finally 语句块。简单来说，try 不允许单独使用，必须和 catch 或 finally 组合使用，catch 和 finally 也不能单独使用。

```java 
try {
    // 可能会发生异常的代码块
} catch (Exception e1) {
    // 捕获并处理try抛出的异常类型Exception
} catch (Exception2 e2) {
    // 捕获并处理try抛出的异常类型Exception2
} finally {
    // 无论是否发生异常，都将执行的代码块
}

```

Java 7 以后，`catch` 多种异常时，也可以像下面这样简化代码：

```java 
try {
    // 可能会发生异常的代码块
} catch (Exception | Exception2 e) {
    // 捕获并处理try抛出的异常类型
} finally {
    // 无论是否发生异常，都将执行的代码块
}

```



6、自定义异常
自定义异常，就是定义一个类，去继承 Throwable 类或者它的子类。

7、异常链