程序运行过程中可能会出现异常情况，比如被0除、对负数计算平方根等，还有可能会出现致命的错误，比如内存不足，磁盘损坏无法读取文件等，对于异常和错误情况的处理，统称为异常处理。

Java异常处理主要通过5个关键字控制：try、catch、throw、throws和finally：
try：试试它所包含的代码段中是否会发生异常；
catch：当有异常时抓住它，并进行相应的处理，使程序不受异常的影响而继续执行下去；
throw：是在程序中明确引发异常；
throws：是如果一个方法可以引发异常，而它本身并不对该异常处理，那么它必须将这个异常抛给调用它的方法；
finally：是无论发不发生异常都要被执行的代码

    关键字:throw,throws,try和catch的用法如下：
        1、throws出现在方法的声明中，表示该方法可能会抛出的异常，允许throws后面跟着多个异常类型
        2、throw出现在方法体中，用于抛出异常。当方法在执行过程中遇到异常情况时，将异常信息封装为异常对象，然后throw。
        3、try出现在方法体中，它自身是一个代码块，表示尝试执行代码块的语句。如果在执行过程中有某条语句抛出异常，那么代码块后面的语句将不被执行。
        4、catch出现在try代码块的后面，自身也是一个代码块，用于捕获异常try代码块中可能抛出的异常。catch关键字后面紧接着它能捕获的异常类型，所有异常类型的子类异常也能被捕获。
Java7引入了新的try(resource)，只需要编写try语句，编译器自动关闭资源，例如

```Java
public void readFile() throws IOException {
    try (InputStream input = new FileInputStream("src/readme.txt")) {
        int n;
        while ((n = input.read()) != -1) {
            System.out.println(n);
        }
    } // 编译器在此自动为我们写入finally并调用close()
}
```

实际上，编译器并不会特别地为`InputStream`加上自动关闭。编译器只看`try(resource = ...)`中的对象是否实现了`java.lang.AutoCloseable`接口，如果实现了，就自动加上`finally`语句并调用`close()`方法。`InputStream`和`OutputStream`都实现了这个接口，因此，都可以用在`try(resource)`中。



















————————————————
版权声明：本文为CSDN博主「zhouyong80」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/zhouyong80/article/details/1907799